from enum import Enum, auto

class STORAGE_CLASS(Enum):
    STANDARD = "STANDARD"
    STANDARD_IA = "STANDARD_IA"
    ONEZONE_IA = "ONEZONE_IA"
    INTELLIGENT_TIERING = "INTELLIGENT_TIERING"
    GLACIER = "GLACIER"
    DEEP_ARCHIVE = "DEEP_ARCHIVE"

class STATE(Enum):
    DOWNLOADING = "DOWNLOADING"
    COMPRESSING = "COMPRESSING"
    UPLOADING = "UPLOADING"
    DONE = "DONE"
