env:
  PROJECT_ID: sml-gke-iac
  ECR_URL: 585008071989.dkr.ecr.eu-west-1.amazonaws.com/org-gdrive-backup
  AWS_REGION: eu-west-1

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Install uv"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"
      - name: "Run Tests"
        run: |
          sudo apt-get update && sudo apt-get install -y gzip pigz lz4
          uv sync --frozen
          source .venv/bin/activate
          python3 -m unittest discover -s tests
  build:
    runs-on: ubuntu-latest
    name: Build OCI image
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: "auth"
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION}} | docker login --username AWS --password-stdin ${{ env.ECR_URL }}
      - name: Build container
        run: |
          docker build -t ${ECR_URL}:${GITHUB_RUN_NUMBER} .
      - name: Push container
        run: |
          docker push ${ECR_URL}:${GITHUB_RUN_NUMBER}
