env:
  PROJECT_ID: sml-gke-iac
  ARTIFACT_REGISTRY: europe-west2-docker.pkg.dev
  SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SA_KEY }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build OCI image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_JSON }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Build container
        run: |
          docker build -t ${ARTIFACT_REGISTRY}/${PROJECT_ID}/org-gdrive-backup/org-gdrive-backup:${GITHUB_RUN_NUMBER} .          
      - name: Push container
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          docker push ${ARTIFACT_REGISTRY}/${PROJECT_ID}/org-gdrive-backup/org-gdrive-backup:${GITHUB_RUN_NUMBER}    