env:
  PROJECT_ID: sml-gke-iac
  ARTIFACT_REGISTRY: europe-west2-docker.pkg.dev

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build OCI image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Run Tests'
        run: |
          sudo apt-get update && sudo apt-get install -y gzip pigz lz4
          uv sync --frozen
          source .venv/bin/activate
          python3 -m unittest discover -s tests
      - name: Build container
        run: |
          docker build -t ${ARTIFACT_REGISTRY}/${PROJECT_ID}/org-gdrive-backup/org-gdrive-backup:${GITHUB_RUN_NUMBER} .
      - name: Push container
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          docker push ${ARTIFACT_REGISTRY}/${PROJECT_ID}/org-gdrive-backup/org-gdrive-backup:${GITHUB_RUN_NUMBER}
